package com.itacademy.users.repositories;

import com.itacademy.domain.entities.User;
import com.itacademy.domain.factories.UserFactory;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.Objects;

@Component

@RequiredArgsConstructor
final class UserMappers {

    private final UserFactory userFactory;

    public User toDomain(UserEntity entity) {
        return userFactory.createUser(
                Math.toIntExact(Objects.requireNonNull(entity.getId())),
                Objects.requireNonNull(entity.getRankingPosition()),
                Objects.requireNonNull(entity.getName())
        );
    }

    public UserEntity toEntity(User user) {
        return new UserEntity(
                user.getId() == null ?
                        null : // Id can be null in order to have it autogenerated
                        Long.valueOf(user.getId()),
                user.getRankingPosition(),
                user.getName()
        );
    }

}
