package com.itacademy.users.repositories;

import com.itacademy.domain.entities.UserImpl;
import org.springframework.stereotype.Component;

import java.util.Objects;

@Component
final class UserMappers {

    static public User toDomain(UserEntity entity) {
        return new UserImpl(
                Math.toIntExact(Objects.requireNonNull(entity.getId())),
                Objects.requireNonNull(entity.getRankingPosition()),
                Objects.requireNonNull(entity.getName())
        );
    }

    static public UserEntity toEntity(User user) {
        return new UserEntity(
                user.getId() == null ?
                        null : // Id can be null in order to have it autogenerated
                        Long.valueOf(user.getId()),
                user.getRankingPosition(),
                user.getName()
        );
    }

}
